name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
    - 
      name: docker login
      uses: actions/checkout@v3
      with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: user/app:latest
  #build:  
  # runs-on: ubuntu-latest
  # steps :
  #  - name: Build the Docker image
  #    run: docker build . --file Dockerfile --tag manxomatt/serverless-framework:v1.0
  #    
  #  - name: Docker Push
  #    run: docker push manxomatt/serverless-framework:v1.0
